name: Publish
on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Build
      run: pnpm install
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: node
        package-name: test-release-please
    - run: npm publish
      if: ${{ steps.release.outputs.release_created }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}